name: 'LeccePrima'
description: 'LeccePrima action '
inputs:
  db-directory:  # id of input
    description: 'The database directory'
    required: true
    default: 'lecceprima-rss-db'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'